"""Build the public research pages from the versioned review release."""
from pathlib import Path
from html import escape
import json,hashlib,shutil,zipfile
ROOT=Path(__file__).resolve().parents[1];D=ROOT/'dist';R=ROOT/'release';VERSION='0.5'
# Release 0.5 is immutable. Website edits must never rewrite its ZIP or manifest.
zipname='MQM_RESEARCH_RELEASE_0.5.zip'
ziphash=hashlib.sha256((D/zipname).read_bytes()).hexdigest()
assert ziphash=='12479c3490d11faa768f246b5d296630fa656365ada362a243f0ad0e8bb5976b'
manifest=json.loads((R/'MANIFEST_SHA256.json').read_text())
for name,digest in manifest.items():
 assert hashlib.sha256((R/name).read_bytes()).hexdigest()==digest, name
for name in ['CITATION.cff','MANIFEST_SHA256.json','branches.json','schema/branch.schema.json','expected/subsystem_algebra.json','expected/x5_envelope.json','docs/MISSING_FILES.md','docs/ENTANGLER_LEMMA.pdf']:
 dest=D/'release'/name;dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(R/name,dest)
# Old public documents become withdrawal notices; archival bytes stay in Git.
for name in ['MQM_PUBLIC_EVIDENCE_UPDATE_v0.2.md','MQM_PUBLIC_PHASE_INTEGRATION_v0.3.md','MQM_TECHNICAL_EVALUATION_BRIEF_v0.1.md']:
 (D/name).write_text('# Superseded public presentation\n\nThis historical document is withdrawn from current presentation. The unreplayable memory table is not current evidence. See the [current consolidated release](/replay/). Original versions remain in source history.\n')
old=D/'MQM_PUBLIC_REVIEW_KIT_v0.1.zip'
if old.exists():old.unlink()
NAV=[('/','Overview'),('/research/','Research'),('/tracker/','Tracker'),('/updates/','Updates'),('/codes/','Codes'),('/replay/','Replay'),('/experiments/','Experiments'),('/compare/','Compare')]
def page(path,title,description,body):
 nav=''.join(f'<a href="{href}"'+(' aria-current="page"' if path==href else '')+f'>{label}</a>' for href,label in NAV)
 s=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} · MQM</title><meta name="description" content="{escape(description)}"><meta name="theme-color" content="#0b151b"><meta property="og:title" content="{escape(title)} · MQM"><meta property="og:description" content="{escape(description)}"><meta property="og:type" content="website"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"></head><body><a class="skip" href="#main">Skip to content</a><header><div class="header wrap"><a href="/" class="brand">MQM<small>Mayes Quantum Method</small></a><nav aria-label="Main navigation">{nav}</nav></div></header><main id="main" class="wrap">{body}</main><footer class="footer wrap"><div><p>Benjamin Walker Mayes</p><p>Code release0.5 · Architecture record7 October2026</p></div><div><a href="/origin/">Research origin</a> · <a href="/release/CITATION.cff" download>Cite this release</a><p>No hardware result. No claimed advantage.</p></div></footer></body></html>'''
 target=D/(path.strip('/')+'/index.html' if path!='/' else 'index.html');target.parent.mkdir(parents=True,exist_ok=True);target.write_text(s)
def heading(label,title,lead):return f'<div class="kicker">{label}</div><h1>{title}</h1><p class="lead">{lead}</p>'
def section(title,body,id=''):return f'<section class="section"'+(f' id="{id}"' if id else '')+f'><h2>{title}</h2>{body}</section>'
def table(caption,headers,rows):return '<div class="table-scroll" role="region" aria-label="'+caption+'" tabindex="0"><table><caption>'+caption+'</caption><thead><tr>'+''.join('<th scope="col">'+x+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr><th scope="row">'+row[0]+'</th>'+''.join('<td>'+x+'</td>' for x in row[1:])+'</tr>' for row in rows)+'</tbody></table></div>'
button=f'<a class="button" href="/{zipname}" download>Download the review release</a>'
missing='<div class="boundary"><p><strong>Memory table withdrawn:</strong> schedule/recovery JSON and full raw-trial outputs are absent. No replayable memory-performance result is published.</p></div>'
home=heading('Research-stage evaluation method','Quantum computing: codes and autonomous control.','MQM develops inspectable quantum-code and finite-control architecture models. Replayable algebra, scoped conditional proofs and numerical constructions. No hardware result. No claimed advantage.')
home+='<p class="next-milestone"><strong>Next milestone:</strong> certify the second-order thermal response at the unchanged temperature target. <a href="/tracker/">Architecture gates</a>. The separate code track awaits external replay of release0.5.</p>'
home+='<div class="actions">'+button+'<a href="/codes/">Inspect the code definitions</a></div><p class="metadata">Review materials available at no charge. Useful outcomes: an independent replay, a written counterexample, or a clearly identified missing assumption.</p>'
home+=section('Three distinct branches','''<div class="cards"><article class="card"><span class="label">RESTRICTED SINGLE-X RECOVERY</span><h3>[[4,1,1]]</h3><p>Core-X: four data qubits. Three active ancillas in the selected pair-parity recovery circuit.</p><p>Quantum distance one. A raw triple-Z face measures logical Z; phase errors remain unprotected.</p><a href="/codes/#repetition-four">Generators and decoder</a></article><article class="card"><span class="label">CONTROLLER CONFORMANCE</span><h3>5-bit repetition<br>+ 4 ancillas</h3><p>Core-X5: five data qubits, including a center and four outer sites. Nine qubits in the reference circuit.</p><p>Quantum distance one. Not the perfect [[5,1,3]] code. The checked envelope is X-only.</p><a href="/codes/#repetition-five">Envelope and failures</a></article><article class="card"><span class="label">EXACT SUBSYSTEM ALGEBRA</span><h3>Subsystem [[8,1,3]]</h3><p>Eight data qubits, one protected logical qubit, three gauge qubits within the register. Extraction ancillas are additional.</p>'''+missing+'''<a href="/codes/#subsystem">Algebra and missing implementation</a></article></div>''')
home+=section('The entangler boundary belongs here.','<p>The supplied searches found no gauge-preserving logical entangler in three tested transversal/pairwise Clifford families. This is a restricted-family obstruction, not a universal impossibility result. A complete noisy logical CNOT remains unestablished.</p><a href="/release/docs/ENTANGLER_LEMMA.pdf">Read the one-page conditional lemma</a>')
home+=section('Scope of the method','<div class="two-col"><div><h3>Available for review</h3><p>Small repetition and subsystem code definitions; a five-step review workflow; exact algebra and finite failure envelopes; prepared experiment drafts.</p></div><div><h3>Not established</h3><p>A quantum platform, a protected X5 memory under general Pauli noise, an executed QPU experiment, a hardware-ready native 3D design, or an advantage over a matched baseline.</p></div></div><p>K₄ is planar. A tetrahedral drawing does not establish a coupling, timing, readout, or error-control benefit.</p>')
page('/','Quantum computing research','Three code sketches, two canonical replay entry points, and unexecuted experiments. No hardware result or claimed advantage.',home)
branches=json.loads((R/'branches.json').read_text())
codes=heading('Code definitions','Resources, operators, and limits.','Notation leads; branch names follow. Data qubits, gauge degrees of freedom, and extraction ancillas are counted separately.')
codes+=table('Branch resource and distance definitions',['Branch','Data','Gauge','Ancillas','Distance'],[['[[4,1,1]] · Core-X','4','0','3 in selected circuit','Unrestricted quantum: 1'],['5-bit repetition · Core-X5','5','0','4','Unrestricted quantum: 1'],['Subsystem [[8,1,3]]','8','3 within data','Not fixed; additional','Dressed subsystem: 3']])
codes+='<p>The source’s four-entry convention is [[n,k,d,r]] = [[8,1,3,3]]. Public notation uses [[8,1,3]] with the three gauge qubits stated explicitly. A four-data + four-ancilla apparatus is a different object from this eight-data code.</p><p><a href="/release/branches.json">Branch records (JSON)</a> · <a href="/release/schema/branch.schema.json">Common branch schema</a></p>'
for branch,id,title,detail in zip(branches,['repetition-four','repetition-five','subsystem'],['[[4,1,1]] · Core-X','5-bit repetition + 4 ancillas · Core-X5','Subsystem [[8,1,3]] · three gauge qubits'],[
'<p>In the computational basis, single-X errors have distinguishable ideal syndromes. ZIII is a weight-one logical error. Raw triple-Z faces act as logical Z: separately measuring them is not equivalent to measuring a safe pair product.</p>',
'<p>Sixteen clean X patterns of weight at most two decode in the ideal model. For one incoming X and one named X-type extraction fault, 800 labeled cases release 750 zero-X and 50 one-X residuals. A released boundary is correctable within the model; it is not a clean-state certificate.</p><div class="boundary"><p>Thirty weight-two + new-X witnesses produce residual logical XXXXX. General Pauli fault tolerance is not established: the prior 120-case audit found 24 multi-data hooks and 80 phase-bearing outcomes.</p></div><p>Forty simulator fault labels include duplicate operational effects. The replay is deterministic conformance, not a memory benchmark or proof of phase protection.</p>',
missing+'<p>The Stim notebook enumerates phase-quotiented Pauli labels, verifies center rank four and gauge rank ten, and finds no dressed logical of weight one or two. The weight-three witness is IIIIIXXZ. This establishes code algebra, not noisy extraction or composition.</p><p>The new ideal-center reference decoder corrects all 24 single-data Pauli errors with ideal syndrome information. It is not the missing historical flag decoder or a restoration of the memory simulation.</p>'
]):
 body=detail+'<h3>Operators</h3><p>Character order follows the branch’s data register; X5 places the center first.</p><pre>Center generators\n'+ '\n'.join(branch['generators']['center'])+'\n\nLogical X: '+branch['logicals']['X']+'\nLogical Z: '+branch['logicals']['Z']+'</pre>'
 if branch['n_gauge']:body+='<pre>Additional gauge generators\n'+'\n'.join(branch['generators']['gauge'][4:])+'</pre>'
 body+='<details><summary>Decoder definition and lookup</summary><p>'+branch['decoder']['scope']+'</p><pre>'+escape(json.dumps(branch['decoder']['lookup'],indent=2))+'</pre><p>Unrecognized syndrome: '+branch['decoder']['unrecognized_syndrome']+'</p></details>'
 figure_name={'repetition-four':'core-x','repetition-five':'core-x5','subsystem':'subsystem'}[id]
 figure_note={'repetition-four':'Data q0-q3; ancillas q4-q6. Three safe pair-parity checks; raw triple-Z faces are not measured.','repetition-five':'Data q0-q4, with center q0; ancillas q5-q8. Four pair-parity checks in one ideal round; no adaptive controller is shown.','subsystem':'Data q0-q7. Ideal MPP measurements of four commuting center generators. This abstract figure has no extraction ancillas and is not the missing gauge-measurement schedule.'}[id]
 body+='<h3>One ideal syndrome round</h3><figure class="circuit-figure"><div class="circuit-scroll" role="region" aria-label="Ideal circuit diagram" tabindex="0"><img src="/circuits/'+figure_name+'.svg" alt="'+figure_note+'"></div><figcaption>'+figure_note+' No noise, idle durations or device implementation is modeled. <a href="/circuits/'+figure_name+'.stim" download>Stim source</a>.</figcaption></figure>'
 if id=='subsystem':
  body+='<h3>Restricted entangler search</h3><p>Source-reported enumeration; not rerun in this release. No gauge-preserving logical entangler was found in the listed families.</p>'+table('Two-block pairwise Clifford search families',['Family','Maps tested','Gauge-preserving','Entangling'],[['Identical two-qubit symplectic Clifford map on all eight corresponding pairs','720','2','0'],['Pair-specific {I, CNOT A-to-B, CNOT B-to-A, CZ}','65,536','1','0'],['Same pair-specific alphabet, plus SWAP','390,625','2','0']])+'<p>These counts do not exclude arbitrary circuits, non-Clifford gates, ancilla-assisted methods, or temporary-gauge surgery. A complete noisy logical CNOT remains unestablished. <a href="/release/docs/ENTANGLER_LEMMA.pdf">Conditional lemma and evidence boundary</a>.</p>'
 codes+=section(title,body,id)
codes+=section('Related QEC foundations','<p>These references supply standard formalism and comparison context. They do not validate MQM or constitute a performance comparison.</p><ul><li><a href="https://arxiv.org/abs/quant-ph/9705052">Gottesman — Stabilizer Codes and Quantum Error Correction</a></li><li><a href="https://arxiv.org/abs/quant-ph/0508131">Poulin — Stabilizer Formalism for Operator Quantum Error Correction</a></li><li><a href="https://arxiv.org/abs/quant-ph/0506023">Bacon — Operator Quantum Error Correcting Subsystems for Self-Correcting Quantum Memories</a></li><li><a href="https://arxiv.org/abs/1208.0928">Fowler et al. — Surface codes: Towards practical large-scale quantum computation</a></li><li><a href="https://arxiv.org/abs/1808.02892">Litinski — A Game of Surface Codes</a></li></ul>')
page('/codes/','Code definitions','Generators, resource counts, distance witnesses and scoped decoder definitions for three separate code sketches.',codes)
replay=heading('One release · two canonical replay entry points','Replay a claim. Keep its boundary.','The consolidated release contains the algebra notebook, X5 envelope replay, expected JSON, branch schema, circuit drafts, source provenance and file hashes.')
replay+='<div class="actions">'+button+'<a href="/MQM_RESEARCH_RELEASE_0.5.sha256">ZIP checksum</a></div><p class="metadata">MQM 0.5 · 18 September 2026 · Tested with Python 3.12.14, Stim 1.15.0, NumPy 2.3.5.</p><p class="hash">SHA-256: '+ziphash+'</p>'
replay+=table('Canonical replay artifacts',['Entry point','Checked here','Not checked'],[['artifacts/subsystem_algebra.ipynb','Stim Pauli algebra, dressed distance three, weight-three witness; new ideal-syndrome reference lookup.','No noisy extraction, historical flag decoder, memory sweep or logical gate composition.'],['artifacts/x5_envelope.py','1,312 round-translation cases; 16 clean patterns; 800 incoming-X cases; 30 logical-failure witnesses.','No general Pauli protection, stochastic memory model, hardware shots or independent replication.']])
replay+=section('Run and compare','<pre>python -m pip install -r requirements.txt\npython -B support/verify_release.py\npython -B support/run_notebook.py\npython -B artifacts/x5_envelope.py</pre><p>Run from the extracted MQM_0.5 folder. The verifier checks hashes and compares parsed outputs with the expected JSON. Jupyter is optional; the lightweight runner executes the notebook’s code cells.</p><p><a href="/release/expected/subsystem_algebra.json">Expected subsystem JSON</a> · <a href="/release/expected/x5_envelope.json">Expected X5 JSON</a> · <a href="/release/MANIFEST_SHA256.json">File manifest</a></p><p>The X5 adapter reinitializes computational-basis frames between rounds. It verifies the declared X-only model; it does not establish preservation of arbitrary logical coherence. Stim simulator introspection is not experimental readout.</p>')
replay+=section('Missing inputs and withdrawn numbers',missing+'<ul><li><code>MQM_K4_8Q_FAULT_TOLERANT_GAUGE_MEASUREMENT_SCHEDULE_v0.2_LOCK.json</code>: missing schedule/recovery contract, including flag lookup.</li><li>Full memory-sweep raw outputs and run provenance: missing; a complete filename inventory has not been recovered.</li><li>A declared noisy implementation with idle, reset, measurement, crosstalk and matched-baseline accounting: not frozen.</li></ul><p>The prior table is withdrawn from current presentation. Its values are not claimed to be disproved; they are unavailable as replayable evidence. Prior release history is retained. No memory-performance estimate appears in the current review download.</p><a href="/release/docs/MISSING_FILES.md">Read the explicit missing-file list</a>')
replay+=section('Five-step review workflow','<ol class="workflow"><li><strong>1. Define</strong>Fix branch, task, error assumptions and resource budget.</li><li><strong>2. Verify</strong>Check operators, distance and counterexamples.</li><li><strong>3. Compile</strong>Specify interactions, measurements, reset and feedback.</li><li><strong>4. Stress</strong>Record residuals, failures and readout limitations.</li><li><strong>5. Compare</strong>Use a frozen task, noise model and matched baseline.</li></ol><p>The two replay entry points cover selected checks, not this entire workflow. Review success is an independent replay, a reproducible disagreement, or a written counterexample.</p>')
page('/replay/','Replay and missing inputs','One dated review release with two canonical replay artifacts, expected outputs and explicit missing-file boundaries.',replay)
experiments=heading('Experimental status','Prepared does not mean executed.','Neither track has QPU data in the supplied evidence. No experimental acceptance rule or independent preregistration is asserted by this release.')
experiments+=section('Track A · trapped-ion conformance','<span class="pill">PREPARED DRAFT · NOT EXECUTED</span><p>A nine-qubit logical test of the X-only repetition controller. It does not demonstrate native tetrahedral hardware or a protected memory under general Pauli noise.</p><h3>A bounded first review</h3><p>The release includes a version-frozen 20-circuit draft inventory: 16 clean X-pattern syndrome checks and four baseline/control templates. The logical Stim files are parseable and their ideal expectations are checked. They are not vendor-compiled pulse schedules.</p><p>Start with the 16 patterns and a paired coherence/crosstalk control review. The historical 1,450-variant inventory is not the first execution request. Single-round syndrome circuits do not themselves implement the full adaptive controller.</p><h3>Before an experimental freeze</h3><ul><li>A named collaborator, mapping, interaction schedule and compiled circuits.</li><li>Calibrated gate, idle, measurement/reset and crosstalk behavior.</li><li>Matched control durations, shot counts, loss handling and decoder latency.</li><li>Predeclared acceptance and rejection rules, then non-constructor review.</li></ul><p>These remain open. No QPU work has been submitted.</p>')
experiments+=section('Track B · native 3D geometry','<span class="pill">GEOMETRY PROPOSAL · NOT EXECUTED</span><p>A tetrahedral-plus-center placement and ancilla motion proposal. No apparatus, calibrated fidelity model, or demonstrated state-sensitive 0/1/loss readout is supplied. It is not an offered work package.</p><p>The proposed partner-switch path λR is a geometric length: R is the center-to-vertex radius and λ the approach fraction. It is not a gate time or fidelity. A physical specification still needs site separations, drive parameters, crosstalk dynamics, timing and readout/control constraints.</p><p>Gates in a native 3D register with ancillas moved to a readout zone must be reported separately from static multilayer readout. No such device capability is claimed here.</p>')
page('/experiments/','Unexecuted experiment drafts','Track A is a bounded controller-conformance draft. Track B remains a geometry proposal. Both are not executed.',experiments)
compare=heading('Comparison status','No frozen comparison yet.','No performance table or advantage claim is published.')+'<div class="empty"><h2>Awaiting a declared baseline</h2><p>A comparison requires a named code and task, resource accounting, circuit/decoder definitions, noise including idle and readout, uncertainty treatment, and a frozen acceptance rule.</p><p>Those inputs are not complete. This page remains empty of benchmark results.</p><a href="/replay/">Inspect the available checks and missing inputs</a></div>'
page('/compare/','Comparison pending','No matched-baseline result is published. Task, noise, resources and acceptance remain to be frozen.',compare)
origin=heading('Research origin','Motivation, not derivation.','MQM began within Benjamin Walker Mayes’s Unified Dynamics research. Tetrahedral adjacency, face closure, packet-local transport and branch structure motivated preserving three-dimensional relationships long enough to test them. Those concepts do not derive a qubit implementation or validate a code, circuit or device. Every MQM claim must stand on its stated QEC mathematics, replayable checks and, where applicable, independent hardware evidence. Physical promotion remains 0.')
origin+='<div class="actions"><a href="/codes/">Return to the code definitions</a></div>'
page('/origin/','Research origin','A single account of MQM’s research motivation; no inference of hardware validation or physical identity.',origin)
(D/'favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="5" fill="#0b151b"/><path d="M16 5 4 25h24ZM16 5v14L4 25m12-6 12 6" fill="none" stroke="#92decf" stroke-width="1.5"/></svg>')
print(json.dumps({'pages':6,'release_zip':zipname,'zip_sha256':ziphash,'manifest_files':len(manifest)}))

from build_session_update import build
build(ROOT)
